AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  python-lambda-hub-websocket-auth
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-lambda-hub-websocket-auth-on-connect
      CodeUri: connect/
      Handler: on_connect_lambda.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: LambdaApiGatewayWebSocketAuth # Nome da sua tabela DynamoDB.
          SIGNING_SECRET_NAME: websocket-signing-key # Nome do segredo a ser criado no AWS Secrets Manager.
          AWS_REGION: us-east-1 # Podera ser definido, de acordo com a localidade a ser estabelecida
      Tags:
        Project-name:
  DisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-lambda-hub-websocket-auth-on-disconnect
      CodeUri: disconnect/
      Handler: on_disconnect_lambda.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: LambdaApiGatewayWebSocketAuth
      Tags:
        Project-name:
  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-lambda-hub-websocket-auth-on-send-message
      CodeUri: message/
      Handler: on_send_message_lambda.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: LambdaApiGatewayWebSocketAuth
          WS_ENDPOINT: localhost # A alterar
      Tags:
        Project-name:
